name: nightly

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Set nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Format
        run: cargo fmt --all -- --check
